name: AI Repository Curator

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'curator_v7.py'
      - 'generate_website.py'
      - 'config.json'
      - '.github/workflows/curator.yml'
      - 'requirements.txt'

jobs:
  curate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create config if it does not exist
      run: |
        if [ ! -f config.json ]; then
          echo '{}' > config.json
        fi

    - name: Run Curator Script
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: python curator_v7.py

    - name: Generate Website Files
      run: python generate_website.py

    - name: Disable Jekyll
      run: touch ./docs/.nojekyll

    - name: Setup GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

    # --- FIX IS HERE ---
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        
        # Check if there are any changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          # Pull the latest changes from the remote to avoid conflicts
          git pull --rebase
          
          # Commit the new files
          git commit -m "🤖 Chore: Auto-update curator results and website"
          
          # Push the changes
          git push
        fi
